// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    user_id, name, type, currency, opening_balance, opened_at,
    credit_limit, statement_close_day, due_day, interest_rate, term_months
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, name, type, currency, opening_balance, opened_at, credit_limit, statement_close_day, due_day, interest_rate, term_months, created_at, updated_at
`

type CreateAccountParams struct {
	UserID            string              `json:"user_id"`
	Name              string              `json:"name"`
	Type              AccountType         `json:"type"`
	Currency          string              `json:"currency"`
	OpeningBalance    decimal.Decimal     `json:"opening_balance"`
	OpenedAt          pgtype.Date         `json:"opened_at"`
	CreditLimit       decimal.NullDecimal `json:"credit_limit"`
	StatementCloseDay pgtype.Int2         `json:"statement_close_day"`
	DueDay            pgtype.Int2         `json:"due_day"`
	InterestRate      decimal.NullDecimal `json:"interest_rate"`
	TermMonths        pgtype.Int2         `json:"term_months"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.OpeningBalance,
		arg.OpenedAt,
		arg.CreditLimit,
		arg.StatementCloseDay,
		arg.DueDay,
		arg.InterestRate,
		arg.TermMonths,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.OpenedAt,
		&i.CreditLimit,
		&i.StatementCloseDay,
		&i.DueDay,
		&i.InterestRate,
		&i.TermMonths,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.UserID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, name, type, currency, opening_balance, opened_at, credit_limit, statement_close_day, due_day, interest_rate, term_months, created_at, updated_at FROM accounts WHERE id = $1 AND user_id = $2
`

type GetAccountParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.OpenedAt,
		&i.CreditLimit,
		&i.StatementCloseDay,
		&i.DueDay,
		&i.InterestRate,
		&i.TermMonths,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, user_id, name, type, currency, opening_balance, opened_at, credit_limit, statement_close_day, due_day, interest_rate, term_months, created_at, updated_at FROM accounts WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListAccounts(ctx context.Context, userID string) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.OpeningBalance,
			&i.OpenedAt,
			&i.CreditLimit,
			&i.StatementCloseDay,
			&i.DueDay,
			&i.InterestRate,
			&i.TermMonths,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts SET
    name = $3,
    currency = $4,
    credit_limit = $5,
    statement_close_day = $6,
    due_day = $7,
    interest_rate = $8,
    term_months = $9,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, type, currency, opening_balance, opened_at, credit_limit, statement_close_day, due_day, interest_rate, term_months, created_at, updated_at
`

type UpdateAccountParams struct {
	ID                pgtype.UUID         `json:"id"`
	UserID            string              `json:"user_id"`
	Name              string              `json:"name"`
	Currency          string              `json:"currency"`
	CreditLimit       decimal.NullDecimal `json:"credit_limit"`
	StatementCloseDay pgtype.Int2         `json:"statement_close_day"`
	DueDay            pgtype.Int2         `json:"due_day"`
	InterestRate      decimal.NullDecimal `json:"interest_rate"`
	TermMonths        pgtype.Int2         `json:"term_months"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Currency,
		arg.CreditLimit,
		arg.StatementCloseDay,
		arg.DueDay,
		arg.InterestRate,
		arg.TermMonths,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.OpenedAt,
		&i.CreditLimit,
		&i.StatementCloseDay,
		&i.DueDay,
		&i.InterestRate,
		&i.TermMonths,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
