// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indicators.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const latestIndicator = `-- name: LatestIndicator :one
SELECT id, code, period, value, source, created_at FROM indicators WHERE code = $1 ORDER BY period DESC LIMIT 1
`

func (q *Queries) LatestIndicator(ctx context.Context, code string) (Indicator, error) {
	row := q.db.QueryRow(ctx, latestIndicator, code)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Period,
		&i.Value,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listIndicatorHistory = `-- name: ListIndicatorHistory :many
SELECT id, code, period, value, source, created_at FROM indicators WHERE code = $1 ORDER BY period ASC
`

func (q *Queries) ListIndicatorHistory(ctx context.Context, code string) ([]Indicator, error) {
	rows, err := q.db.Query(ctx, listIndicatorHistory, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Indicator
	for rows.Next() {
		var i Indicator
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Period,
			&i.Value,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIndicator = `-- name: UpsertIndicator :one
INSERT INTO indicators (code, period, value, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code, period) DO UPDATE SET value = EXCLUDED.value, source = EXCLUDED.source
RETURNING id, code, period, value, source, created_at
`

type UpsertIndicatorParams struct {
	Code   string          `json:"code"`
	Period pgtype.Date     `json:"period"`
	Value  decimal.Decimal `json:"value"`
	Source string          `json:"source"`
}

func (q *Queries) UpsertIndicator(ctx context.Context, arg UpsertIndicatorParams) (Indicator, error) {
	row := q.db.QueryRow(ctx, upsertIndicator,
		arg.Code,
		arg.Period,
		arg.Value,
		arg.Source,
	)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Period,
		&i.Value,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}
