// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AccountType string

const (
	AccountTypeCash       AccountType = "cash"
	AccountTypeBank       AccountType = "bank"
	AccountTypeCreditCard AccountType = "credit_card"
	AccountTypeCreditLine AccountType = "credit_line"
	AccountTypeInvestment AccountType = "investment"
	AccountTypeLoan       AccountType = "loan"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type Account struct {
	ID                pgtype.UUID         `json:"id"`
	UserID            string              `json:"user_id"`
	Name              string              `json:"name"`
	Type              AccountType         `json:"type"`
	Currency          string              `json:"currency"`
	OpeningBalance    decimal.Decimal     `json:"opening_balance"`
	OpenedAt          pgtype.Date         `json:"opened_at"`
	CreditLimit       decimal.NullDecimal `json:"credit_limit"`
	StatementCloseDay pgtype.Int2         `json:"statement_close_day"`
	DueDay            pgtype.Int2         `json:"due_day"`
	InterestRate      decimal.NullDecimal `json:"interest_rate"`
	TermMonths        pgtype.Int2         `json:"term_months"`
	CreatedAt         pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz  `json:"updated_at"`
}

type Indicator struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Period    pgtype.Date        `json:"period"`
	Value     decimal.Decimal    `json:"value"`
	Source    string             `json:"source"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RecurringCharge struct {
	ID                        pgtype.UUID        `json:"id"`
	UserID                    string             `json:"user_id"`
	Name                      string             `json:"name"`
	BaseAmount                decimal.Decimal    `json:"base_amount"`
	BasePeriod                pgtype.Date        `json:"base_period"`
	AdjustmentFrequencyMonths int16              `json:"adjustment_frequency_months"`
	IndexCode                 string             `json:"index_code"`
	NextReviewDate            pgtype.Date        `json:"next_review_date"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            string             `json:"user_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	OccurredAt        pgtype.Date        `json:"occurred_at"`
	Amount            decimal.Decimal    `json:"amount"`
	Description       string             `json:"description"`
	Category          pgtype.Text        `json:"category"`
	TransferAccountID pgtype.UUID        `json:"transfer_account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
