// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateRecurringCharge(ctx context.Context, arg CreateRecurringChargeParams) (RecurringCharge, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) error
	DeleteRecurringCharge(ctx context.Context, arg DeleteRecurringChargeParams) error
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	GetRecurringCharge(ctx context.Context, arg GetRecurringChargeParams) (RecurringCharge, error)
	LatestIndicator(ctx context.Context, code string) (Indicator, error)
	ListAccounts(ctx context.Context, userID string) ([]Account, error)
	ListIndicatorHistory(ctx context.Context, code string) ([]Indicator, error)
	ListRecurringCharges(ctx context.Context, userID string) ([]RecurringCharge, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error)
	NetWorth(ctx context.Context, userID string) ([]NetWorthRow, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateRecurringCharge(ctx context.Context, arg UpdateRecurringChargeParams) (RecurringCharge, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpsertIndicator(ctx context.Context, arg UpsertIndicatorParams) (Indicator, error)
}

var _ Querier = (*Queries)(nil)
