// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_charges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createRecurringCharge = `-- name: CreateRecurringCharge :one
INSERT INTO recurring_charges (
    user_id, name, base_amount, base_period, adjustment_frequency_months, index_code, next_review_date
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, base_amount, base_period, adjustment_frequency_months, index_code, next_review_date, created_at, updated_at
`

type CreateRecurringChargeParams struct {
	UserID                    string          `json:"user_id"`
	Name                      string          `json:"name"`
	BaseAmount                decimal.Decimal `json:"base_amount"`
	BasePeriod                pgtype.Date     `json:"base_period"`
	AdjustmentFrequencyMonths int16           `json:"adjustment_frequency_months"`
	IndexCode                 string          `json:"index_code"`
	NextReviewDate            pgtype.Date     `json:"next_review_date"`
}

func (q *Queries) CreateRecurringCharge(ctx context.Context, arg CreateRecurringChargeParams) (RecurringCharge, error) {
	row := q.db.QueryRow(ctx, createRecurringCharge,
		arg.UserID,
		arg.Name,
		arg.BaseAmount,
		arg.BasePeriod,
		arg.AdjustmentFrequencyMonths,
		arg.IndexCode,
		arg.NextReviewDate,
	)
	var i RecurringCharge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BaseAmount,
		&i.BasePeriod,
		&i.AdjustmentFrequencyMonths,
		&i.IndexCode,
		&i.NextReviewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecurringCharge = `-- name: DeleteRecurringCharge :exec
DELETE FROM recurring_charges WHERE id = $1 AND user_id = $2
`

type DeleteRecurringChargeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteRecurringCharge(ctx context.Context, arg DeleteRecurringChargeParams) error {
	_, err := q.db.Exec(ctx, deleteRecurringCharge, arg.ID, arg.UserID)
	return err
}

const getRecurringCharge = `-- name: GetRecurringCharge :one
SELECT id, user_id, name, base_amount, base_period, adjustment_frequency_months, index_code, next_review_date, created_at, updated_at FROM recurring_charges WHERE id = $1 AND user_id = $2
`

type GetRecurringChargeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetRecurringCharge(ctx context.Context, arg GetRecurringChargeParams) (RecurringCharge, error) {
	row := q.db.QueryRow(ctx, getRecurringCharge, arg.ID, arg.UserID)
	var i RecurringCharge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BaseAmount,
		&i.BasePeriod,
		&i.AdjustmentFrequencyMonths,
		&i.IndexCode,
		&i.NextReviewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecurringCharges = `-- name: ListRecurringCharges :many
SELECT id, user_id, name, base_amount, base_period, adjustment_frequency_months, index_code, next_review_date, created_at, updated_at FROM recurring_charges WHERE user_id = $1 ORDER BY next_review_date
`

func (q *Queries) ListRecurringCharges(ctx context.Context, userID string) ([]RecurringCharge, error) {
	rows, err := q.db.Query(ctx, listRecurringCharges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringCharge
	for rows.Next() {
		var i RecurringCharge
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.BaseAmount,
			&i.BasePeriod,
			&i.AdjustmentFrequencyMonths,
			&i.IndexCode,
			&i.NextReviewDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringCharge = `-- name: UpdateRecurringCharge :one
UPDATE recurring_charges SET
    name = $3,
    base_amount = $4,
    base_period = $5,
    adjustment_frequency_months = $6,
    index_code = $7,
    next_review_date = $8,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, base_amount, base_period, adjustment_frequency_months, index_code, next_review_date, created_at, updated_at
`

type UpdateRecurringChargeParams struct {
	ID                        pgtype.UUID     `json:"id"`
	UserID                    string          `json:"user_id"`
	Name                      string          `json:"name"`
	BaseAmount                decimal.Decimal `json:"base_amount"`
	BasePeriod                pgtype.Date     `json:"base_period"`
	AdjustmentFrequencyMonths int16           `json:"adjustment_frequency_months"`
	IndexCode                 string          `json:"index_code"`
	NextReviewDate            pgtype.Date     `json:"next_review_date"`
}

func (q *Queries) UpdateRecurringCharge(ctx context.Context, arg UpdateRecurringChargeParams) (RecurringCharge, error) {
	row := q.db.QueryRow(ctx, updateRecurringCharge,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.BaseAmount,
		arg.BasePeriod,
		arg.AdjustmentFrequencyMonths,
		arg.IndexCode,
		arg.NextReviewDate,
	)
	var i RecurringCharge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BaseAmount,
		&i.BasePeriod,
		&i.AdjustmentFrequencyMonths,
		&i.IndexCode,
		&i.NextReviewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
