// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, account_id, occurred_at, amount, description, category, transfer_account_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, account_id, occurred_at, amount, description, category, transfer_account_id, created_at
`

type CreateTransactionParams struct {
	UserID            string          `json:"user_id"`
	AccountID         pgtype.UUID     `json:"account_id"`
	OccurredAt        pgtype.Date     `json:"occurred_at"`
	Amount            decimal.Decimal `json:"amount"`
	Description       string          `json:"description"`
	Category          pgtype.Text     `json:"category"`
	TransferAccountID pgtype.UUID     `json:"transfer_account_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.AccountID,
		arg.OccurredAt,
		arg.Amount,
		arg.Description,
		arg.Category,
		arg.TransferAccountID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.OccurredAt,
		&i.Amount,
		&i.Description,
		&i.Category,
		&i.TransferAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, account_id, occurred_at, amount, description, category, transfer_account_id, created_at FROM transactions
WHERE user_id = $1
  AND ($2::date IS NULL OR occurred_at >= $2)
  AND ($3::date IS NULL OR occurred_at <= $3)
ORDER BY occurred_at DESC
`

type ListTransactionsParams struct {
	UserID   string      `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.OccurredAt,
			&i.Amount,
			&i.Description,
			&i.Category,
			&i.TransferAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, user_id, account_id, occurred_at, amount, description, category, transfer_account_id, created_at FROM transactions
WHERE user_id = $1 AND account_id = $2
  AND ($3::date IS NULL OR occurred_at >= $3)
  AND ($4::date IS NULL OR occurred_at <= $4)
ORDER BY occurred_at DESC
`

type ListTransactionsByAccountParams struct {
	UserID    string      `json:"user_id"`
	AccountID pgtype.UUID `json:"account_id"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount,
		arg.UserID,
		arg.AccountID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.OccurredAt,
			&i.Amount,
			&i.Description,
			&i.Category,
			&i.TransferAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const netWorth = `-- name: NetWorth :many
SELECT
    a.id AS account_id,
    a.name AS name,
    a.type AS type,
    a.currency AS currency,
    (a.opening_balance + COALESCE(SUM(t.amount), 0))::numeric(18, 2) AS balance
FROM accounts a
LEFT JOIN transactions t ON t.account_id = a.id
WHERE a.user_id = $1
GROUP BY a.id, a.name, a.type, a.currency, a.opening_balance
ORDER BY a.name
`

type NetWorthRow struct {
	AccountID pgtype.UUID     `json:"account_id"`
	Name      string          `json:"name"`
	Type      AccountType     `json:"type"`
	Currency  string          `json:"currency"`
	Balance   decimal.Decimal `json:"balance"`
}

func (q *Queries) NetWorth(ctx context.Context, userID string) ([]NetWorthRow, error) {
	rows, err := q.db.Query(ctx, netWorth, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NetWorthRow
	for rows.Next() {
		var i NetWorthRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions SET
    occurred_at = $3,
    amount = $4,
    description = $5,
    category = $6
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, account_id, occurred_at, amount, description, category, transfer_account_id, created_at
`

type UpdateTransactionParams struct {
	ID          pgtype.UUID     `json:"id"`
	UserID      string          `json:"user_id"`
	OccurredAt  pgtype.Date     `json:"occurred_at"`
	Amount      decimal.Decimal `json:"amount"`
	Description string          `json:"description"`
	Category    pgtype.Text     `json:"category"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.OccurredAt,
		arg.Amount,
		arg.Description,
		arg.Category,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.OccurredAt,
		&i.Amount,
		&i.Description,
		&i.Category,
		&i.TransferAccountID,
		&i.CreatedAt,
	)
	return i, err
}
